### PR TITLE
feat: add plot 4 and layout part

### PR DESCRIPTION
**Pull request by xiangwxt**
Add plot 4 in tab 2, and corresponding layout.
issue #31

### CODE REVIEW

**Review by michelle-wms — CHANGES_REQUESTED** [review]
Great to see it running! Some comments: 
- tab seems to have a white space at the bottom, is it possible to try to not have the white space? 
- And can u make abit smaller your plot with altair properties so that we don't need to scroll? something like .properties(width=...........) at the end of your chart 
- Remove the title from altair because you already have a title in the app :)

**Comment by christopheralex** [comment]
@xiangwxt You might have to pull the main again and solve the conflicts so that both the plots are up on the up. 
Overall really great work to get this done in a day 👍

**Review by christopheralex — CHANGES_REQUESTED** [review]
Good to go once merge conflicts are solved and app displays on reviewing server . 
You can let the scrolling for the next stage of development if thats taking time since thats an issue in other plots as well.

**Comment by xiangwxt** [comment]
> Good to go once merge conflicts are solved and app displays on reviewing server . You can let the scrolling for the next stage of development if thats taking time since thats an issue in other plots as well.

Hi Chris, thank you for your review. The conflicts has been solved.

**Comment by xiangwxt** [comment]
> Great to see it running! Some comments:
> 
> * tab seems to have a white space at the bottom, is it possible to try to not have the white space?
> * And can u make abit smaller your plot with altair properties so that we don't need to scroll? something like .properties(width=...........) at the end of your chart
> * Remove the title from altair because you already have a title in the app :)

Hello @michelle-wms Thank you for your suggestions, all three have been solved, please help review the changes.

**Review by christopheralex — APPROVED** [review]
Great work. Looks good to me

**Review by michelle-wms — APPROVED** [review]

**Comment by michelle-wms** [comment]
There's still white space below, but I think it's fine for now! Merged.

**Pull request merged**
