### PR TITLE
Layout changes and added plot2

### PR DESCRIPTION
**Pull request by michelle-wms**
After painful-wrangling and eye-bleeding:
 
- Made layout changes 
- Added artist-widget for tab1
- Added plot2

### CODE REVIEW

**Comment by christopheralex** [comment]
Hey Michelle, the deployment doesn't seem to work for your PR . Can you check the logs on heroku and get it up ?

**Comment by michelle-wms** [comment]
@christopheralex ok it was file reading error - now fixed! please check.

**Comment by christopheralex** [comment]
Looks good but I guess this code removes @jennifer-hoang 's plot . 
Hey @jennifer-hoang, can you work on this branch or give any insights on this PR if this affects your plot in the layout ?

**Comment by jennifer-hoang** [comment]
Hi @michelle-wms, @christopheralex,
I've added my plot back into the layout on this branch, feel free to go ahead with the merging.

**Review by jennifer-hoang — APPROVED** [review]

**Review by christopheralex — APPROVED** [review]
Looks good guys. Thank you :)

**Pull request merged**
